<?php

return [
    'terminos_evento' => [
        'terremoto',
        'sismo',
        'temblor',
        'réplica',
        'epicentro',
    ],
    'terminos_ubicacion' => [
        'venezuela',
        'venezolano',
        'venezolana',
        'caracas',
        'lara',
        'barquisimeto',
        'yaracuy',
        'portuguesa',
        'trujillo',
        'mérida',
        'táchira',
        'zulia',
        'falcón',
        'carabobo',
        'aragua',
        'cojedes',
        'barinas',
        'apure',
        'guárico',
        'miranda',
        'la guaira',
        'sucre',
        'monagas',
        'anzoátegui',
        'nueva esparta',
        'bolívar',
        'amazonas',
        'delta amacuro',
    ],
];